CREATE TABLE IF NOT EXISTS master_company (
  comp_code smallint PRIMARY KEY,
  company_id varchar(50) NOT NULL UNIQUE,
  company_name varchar(100) NOT NULL,
  legal_name varchar(150) NOT NULL,
  address varchar(300) NOT NULL,
  gstin varchar(15) NOT NULL,
  pan varchar(10) NOT NULL,
  state_name varchar(100) NOT NULL,
  state_code varchar(2) NOT NULL,
  cin varchar(30),
  website varchar(100),
  iec varchar(20),
  phone varchar(50),
  email varchar(100),
  bank_name varchar(100),
  bank_branch varchar(100),
  account_name varchar(150),
  account_number varchar(50),
  ifsc varchar(20),
  pi_prefix varchar(10) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

INSERT INTO master_company (
  comp_code,
  company_id,
  company_name,
  legal_name,
  address,
  gstin,
  pan,
  state_name,
  state_code,
  cin,
  website,
  iec,
  phone,
  email,
  bank_name,
  bank_branch,
  account_name,
  account_number,
  ifsc,
  pi_prefix
) VALUES
  (
    1,
    'autopal-jaipur',
    'AUTOPAL',
    'M/s Autolite (India) Limited',
    'E-527-529, RIICO Industrial Area, Sitapura, Tonk Road, Jaipur-302022, Rajasthan',
    '08AABCA4083B1Z4',
    'AABCA4083B',
    'Rajasthan',
    '08',
    'L31506RJ1977PLC001738',
    'www.autopal.com',
    '1309002564',
    '91-141-2771178',
    'ecu@autopal.com',
    'State Bank of India',
    'Sitapura, Jaipur',
    'Autolite (India) Limited',
    '30234567891',
    'SBIN0031025',
    'HAL-'
  ),
  (
    2,
    'autolite',
    'AUTOLITE',
    'Autolite Manufacturing Limited',
    'D-469, Road No. 9A, VKI Area, Jaipur, Rajasthan 302013, India',
    '08AAACA5678L1Z2',
    'AAACA5678L',
    'Rajasthan',
    '08',
    'L31506RJ1977PLC001738',
    'www.autopal.com',
    '1309001128',
    '+91 141 233 1950',
    'commercial@autolite.in',
    'HDFC Bank',
    'M I Road, Jaipur',
    'Autolite Manufacturing Limited',
    '50200034561234',
    'HDFC0000545',
    'AML-'
  )
ON CONFLICT (comp_code) DO UPDATE
SET
  company_id = EXCLUDED.company_id,
  company_name = EXCLUDED.company_name,
  legal_name = EXCLUDED.legal_name,
  address = EXCLUDED.address,
  gstin = EXCLUDED.gstin,
  pan = EXCLUDED.pan,
  state_name = EXCLUDED.state_name,
  state_code = EXCLUDED.state_code,
  cin = EXCLUDED.cin,
  website = EXCLUDED.website,
  iec = EXCLUDED.iec,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  bank_name = EXCLUDED.bank_name,
  bank_branch = EXCLUDED.bank_branch,
  account_name = EXCLUDED.account_name,
  account_number = EXCLUDED.account_number,
  ifsc = EXCLUDED.ifsc,
  pi_prefix = EXCLUDED.pi_prefix,
  is_active = true,
  updated_at = NOW();
